OPENAI_API_KEY="sk-proj-j1h322OGycAeMTtoIlGNT3BlbkFJJbQHtFernvLQJoUs9o3v"
SF_USER='gobinath'
SF_PASSWORD='Gopi@1234'
SF_ACCOUNT='djvklov-tv80439'
SF_WAREHOUSE='COMPUTE_WH'
SF_DATABASE = 'tasty_bytes_sample_data'
SF_SCHEMA = 'raw_pos'
SF_ROLE='ACCOUNTADMIN'